// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.lichee.grpc.example.proto;

public final class StudentProto {
  private StudentProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_HttpRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_HttpRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_HttpResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_HttpResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_StreamRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_StreamRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_StreamResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_StreamResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_StreamResponseList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_StreamResponseList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_StreamRequestInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_StreamRequestInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_StreamResponseInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_StreamResponseInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rStudent.proto\022\004grpc\"\037\n\013HttpRequest\022\020\n\010" +
      "username\030\001 \001(\t\" \n\014HttpResponse\022\020\n\010realna" +
      "me\030\002 \001(\t\"\034\n\rStreamRequest\022\013\n\003age\030\001 \001(\005\"9" +
      "\n\016StreamResponse\022\014\n\004name\030\001 \001(\t\022\013\n\003age\030\002 " +
      "\001(\005\022\014\n\004city\030\003 \001(\t\"B\n\022StreamResponseList\022" +
      ",\n\016streamResponse\030\001 \003(\0132\024.grpc.StreamRes" +
      "ponse\")\n\021StreamRequestInfo\022\024\n\014request_in" +
      "fo\030\001 \001(\t\"+\n\022StreamResponseInfo\022\025\n\rrespon" +
      "se_info\030\001 \001(\t2\247\002\n\016StudentService\022@\n\025getR" +
      "ealnameByUsername\022\021.grpc.HttpRequest\032\022.g" +
      "rpc.HttpResponse\"\000\022A\n\020getStudentsByAge\022\023" +
      ".grpc.StreamRequest\032\024.grpc.StreamRespons" +
      "e\"\0000\001\022M\n\030getStudentsWrapperByAges\022\023.grpc" +
      ".StreamRequest\032\030.grpc.StreamResponseList" +
      "\"\000(\001\022A\n\006biTalk\022\027.grpc.StreamRequestInfo\032" +
      "\030.grpc.StreamResponseInfo\"\000(\0010\001B/\n\035com.l" +
      "ichee.grpc.example.protoB\014StudentProtoP\001" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_grpc_HttpRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_grpc_HttpRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_HttpRequest_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_grpc_HttpResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_grpc_HttpResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_HttpResponse_descriptor,
        new java.lang.String[] { "Realname", });
    internal_static_grpc_StreamRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_grpc_StreamRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_StreamRequest_descriptor,
        new java.lang.String[] { "Age", });
    internal_static_grpc_StreamResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_grpc_StreamResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_StreamResponse_descriptor,
        new java.lang.String[] { "Name", "Age", "City", });
    internal_static_grpc_StreamResponseList_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_grpc_StreamResponseList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_StreamResponseList_descriptor,
        new java.lang.String[] { "StreamResponse", });
    internal_static_grpc_StreamRequestInfo_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_grpc_StreamRequestInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_StreamRequestInfo_descriptor,
        new java.lang.String[] { "RequestInfo", });
    internal_static_grpc_StreamResponseInfo_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_grpc_StreamResponseInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_StreamResponseInfo_descriptor,
        new java.lang.String[] { "ResponseInfo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
